#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '~> 2.2.1'
cookbook 'git'
cookbook 'postgresql', '~> 3.4.20'
cookbook 'rvm',
  git: 'git://github.com/fnichol/chef-rvm.git'
cookbook 'nodejs', '= 1.3.0'
